---
# tasks file for mariadb-server
- name: install mariadb
  yum:
    name:
     - mariadb-server
     - python3-PyMySQL
    state: latest

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started
  notify: start_mariadb_Service

- name: mysql_root_password
  mysql_user:
      login_user: "{{user_name}}"
      login_password: "{{ mysql_root_password }}"
      user: "{{user_name}}"
      check_implicit_admin: true
      password: "{{ mysql_root_password }}"
      host: localhost


- name: install configuration file
  get_url:
    url: "{{my_cnf_file_url}}"
    dest: /var/lib/mysql/
  notify: start_mariadb_Service